### ISSUE TITLE
Limits not enforced for high UIDs

### ISSUE THREAD

**Issue by daurnimator** [hashbang/shell-server#125]
https://github.com/hashbang/shell-server/blob/851233c8800e89587cc74a9d5f8dcd4dd245a767/ansible/tasks/security/main.yml#L24-L27

https://github.com/hashbang/userdb/blob/bed8d007aefaaf9fff7660baa359649a25d5e9bc/schema/sql/schema.sql#L51

**Comment by daurnimator** [comment]
At least autosignups will fail; our sequence runs out: https://github.com/hashbang/userdb/blob/bed8d007aefaaf9fff7660baa359649a25d5e9bc/schema/sql/schema.sql#L19

**Comment by RyanSquared** [comment]
Closed by 229e4a5

**Comment by daurnimator** [comment]
The reason I didn't do this immediately was that I thought UIDs between  `60000` and `65535` were special in some way?

**Comment by RyanSquared** [comment]
They are slightly special in Debian, in that they are reserved for systemd-homed users. However, those users are "just" another user, and since we're not using systemd-homed in any way, there is no reason to *not* restrict them.

The problem we're gonna face is how do we allow users above the 65535 range in our schema, adding a hole in our sequence?
