### ISSUE TITLE
Warrant Canary

### ISSUE THREAD

**Issue by lrvick** [hashbang/shell-server#30]
Being a public service that users need to be able to trust at some level, I feel we should implement a warrant canary somewhere.

Thoughts on wording/placement?

**Comment by davidcox143** [comment]
Could it be as simple as placing a file in the home directories, which could then be removed should something happen?

**Comment by AlissaSquared** [comment]
As commented by daurnimator:

23:32 <~daurnimator> as people are going to be curious about 'now', not 'a week ago'
23:38 <~daurnimator> e.g. it's useful for rsync, because you could download the source now; then in a week when the next warrant canary comes out: build it knowing that it's the source the author intended you to have
23:38 <~daurnimator> with hashbang, you get to know that the government has all your hashbang data; up to a week after the fact.
23:38 <~daurnimator> what's the point?

If anyone has a point they'd like to bring up against this, it's fine by me, but I found this to be a very true statement against having a warrant canary.

**Comment by AlissaSquared** [comment]
Also - @davidcox143 - I'm quite sure there's a legal way that the government can tell us to not access our servers and delete said file. The purpose of a manual warrant canary is so that if it is gone, the government cannot force us to send out the message. An automatic warrant canary, however, can be forced to continue publishing statments.
